name: Update Stock Data

on:
  schedule:
    # Run at 9 AM and 3 PM Jakarta time (UTC+7)
    - cron: '0 2,8 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-stocks:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run stock scraper
      run: |
        cd scripts
        python scraper.py
    
    - name: Generate static HTML
      run: |
        python scripts/generate_static.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add static/data/stocks.json
        git add index.html
        git diff --staged --quiet || git commit -m "Update stock data - $(date +'%Y-%m-%d %H:%M:%S')"
        git push